# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: missile_defense.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15missile_defense.proto\x1a\x1bgoogle/protobuf/empty.proto\"B\n\x0eMissileRequest\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\x12\x0c\n\x04time\x18\x03 \x01(\x05\x12\x0c\n\x04type\x18\x04 \x01(\x05\"\x17\n\tSoldierID\x12\n\n\x02id\x18\x01 \x01(\x05\"!\n\rSoldierStatus\x12\x10\n\x08is_alive\x18\x01 \x01(\x08\"\x1c\n\x0b\x42oolMessage\x12\r\n\x05value\x18\x01 \x01(\x08\"N\n\x12TakeShelterRequest\x12\x12\n\nsoldier_id\x18\x01 \x01(\x05\x12\x11\n\tmissile_x\x18\x02 \x01(\x05\x12\x11\n\tmissile_y\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\xdc\x01\n\x15MissileDefenseService\x12=\n\x12MissileApproaching\x12\x0f.MissileRequest\x1a\x16.google.protobuf.Empty\x12$\n\x06Status\x12\n.SoldierID\x1a\x0e.SoldierStatus\x12\"\n\x06WasHit\x12\n.SoldierID\x1a\x0c.BoolMessage\x12:\n\x0bTakeShelter\x12\x13.TakeShelterRequest\x1a\x16.google.protobuf.Emptyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'missile_defense_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_MISSILEREQUEST']._serialized_start=54
  _globals['_MISSILEREQUEST']._serialized_end=120
  _globals['_SOLDIERID']._serialized_start=122
  _globals['_SOLDIERID']._serialized_end=145
  _globals['_SOLDIERSTATUS']._serialized_start=147
  _globals['_SOLDIERSTATUS']._serialized_end=180
  _globals['_BOOLMESSAGE']._serialized_start=182
  _globals['_BOOLMESSAGE']._serialized_end=210
  _globals['_TAKESHELTERREQUEST']._serialized_start=212
  _globals['_TAKESHELTERREQUEST']._serialized_end=290
  _globals['_EMPTY']._serialized_start=292
  _globals['_EMPTY']._serialized_end=299
  _globals['_MISSILEDEFENSESERVICE']._serialized_start=302
  _globals['_MISSILEDEFENSESERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
